spring.application.name=api_gateway

server.port=8080
logging.level.com.example.api_gateway=Info
logging.level.org.springframework.cloud.gateway=Info


jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3Q=
jwt.expiration-ms=86400000


# Redis

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.connect-timeout=2s

# ── Circuit Breaker: user-service ──────────────────────────────────────────
resilience4j.circuitbreaker.instances.userServiceCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.userServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userServiceCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.userServiceCB.register-health-indicator=true

# ── Circuit Breaker: product-service ───────────────────────────────────────
resilience4j.circuitbreaker.instances.productServiceCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.productServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.productServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.productServiceCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.productServiceCB.register-health-indicator=true



# ── Actuator ─────────────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,circuitbreakers,prometheus,metrics
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# ── Prometheus ────────────────────────────────────────────────────────────────
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true